// Used by Cpu and Disassembler to decode opcodes and handle the instructions
macro_rules! handle_opcode {
($opcode:expr, $this:ident, $mem:ident) => {
    match $opcode {
        0xA9 => $this.lda($mem, AddressMode::Immediate),
        0xA5 => $this.lda($mem, AddressMode::ZeroPage),
        0xB5 => $this.lda($mem, AddressMode::ZeroPageIndexed(Register8::X)),
        0xAD => $this.lda($mem, AddressMode::Absolute),
        0xBD => $this.lda($mem, AddressMode::AbsoluteIndexed(Register8::X)),
        0xB9 => $this.lda($mem, AddressMode::AbsoluteIndexed(Register8::Y)),
        0xA1 => $this.lda($mem, AddressMode::IndexedIndirect(Register8::X)),
        0xB1 => $this.lda($mem, AddressMode::IndirectIndexed(Register8::Y)),

        0xA2 => $this.ldx($mem, AddressMode::Immediate),
        0xA6 => $this.ldx($mem, AddressMode::ZeroPage),
        0xB6 => $this.ldx($mem, AddressMode::ZeroPageIndexed(Register8::Y)),
        0xAE => $this.ldx($mem, AddressMode::Absolute),
        0xBE => $this.ldx($mem, AddressMode::AbsoluteIndexed(Register8::Y)),

        0xA0 => $this.ldy($mem, AddressMode::Immediate),
        0xA4 => $this.ldy($mem, AddressMode::ZeroPage),
        0xB4 => $this.ldy($mem, AddressMode::ZeroPageIndexed(Register8::X)),
        0xAC => $this.ldy($mem, AddressMode::Absolute),
        0xBC => $this.ldy($mem, AddressMode::AbsoluteIndexed(Register8::X)),

        0x85 => $this.sta($mem, AddressMode::ZeroPage),
        0x95 => $this.sta($mem, AddressMode::ZeroPageIndexed(Register8::X)),
        0x8D => $this.sta($mem, AddressMode::Absolute),
        0x9D => $this.sta($mem, AddressMode::AbsoluteIndexed(Register8::X)),
        0x99 => $this.sta($mem, AddressMode::AbsoluteIndexed(Register8::Y)),
        0x81 => $this.sta($mem, AddressMode::IndexedIndirect(Register8::X)),
        0x91 => $this.sta($mem, AddressMode::IndirectIndexed(Register8::Y)),

        0x86 => $this.stx($mem, AddressMode::ZeroPage),
        0x96 => $this.stx($mem, AddressMode::ZeroPageIndexed(Register8::Y)),
        0x8E => $this.stx($mem, AddressMode::Absolute),

        0x84 => $this.sty($mem, AddressMode::ZeroPage),
        0x94 => $this.sty($mem, AddressMode::ZeroPageIndexed(Register8::X)),
        0x8C => $this.sty($mem, AddressMode::Absolute),

        0x69 => $this.adc($mem, AddressMode::Immediate),
        0x65 => $this.adc($mem, AddressMode::ZeroPage),
        0x75 => $this.adc($mem, AddressMode::ZeroPageIndexed(Register8::X)),
        0x6D => $this.adc($mem, AddressMode::Absolute),
        0x7D => $this.adc($mem, AddressMode::AbsoluteIndexed(Register8::X)),
        0x79 => $this.adc($mem, AddressMode::AbsoluteIndexed(Register8::Y)),
        0x61 => $this.adc($mem, AddressMode::IndexedIndirect(Register8::X)),
        0x71 => $this.adc($mem, AddressMode::IndirectIndexed(Register8::Y)),

        0xE9 => $this.sbc($mem, AddressMode::Immediate),
        0xE5 => $this.sbc($mem, AddressMode::ZeroPage),
        0xF5 => $this.sbc($mem, AddressMode::ZeroPageIndexed(Register8::X)),
        0xED => $this.sbc($mem, AddressMode::Absolute),
        0xFD => $this.sbc($mem, AddressMode::AbsoluteIndexed(Register8::X)),
        0xF9 => $this.sbc($mem, AddressMode::AbsoluteIndexed(Register8::Y)),
        0xE1 => $this.sbc($mem, AddressMode::IndexedIndirect(Register8::X)),
        0xF1 => $this.sbc($mem, AddressMode::IndirectIndexed(Register8::Y)),

        0x29 => $this.and($mem, AddressMode::Immediate),
        0x25 => $this.and($mem, AddressMode::ZeroPage),
        0x35 => $this.and($mem, AddressMode::ZeroPageIndexed(Register8::X)),
        0x2D => $this.and($mem, AddressMode::Absolute),
        0x3D => $this.and($mem, AddressMode::AbsoluteIndexed(Register8::X)),
        0x39 => $this.and($mem, AddressMode::AbsoluteIndexed(Register8::Y)),
        0x21 => $this.and($mem, AddressMode::IndexedIndirect(Register8::X)),
        0x31 => $this.and($mem, AddressMode::IndirectIndexed(Register8::Y)),

        0x09 => $this.ora($mem, AddressMode::Immediate),
        0x05 => $this.ora($mem, AddressMode::ZeroPage),
        0x15 => $this.ora($mem, AddressMode::ZeroPageIndexed(Register8::X)),
        0x0D => $this.ora($mem, AddressMode::Absolute),
        0x1D => $this.ora($mem, AddressMode::AbsoluteIndexed(Register8::X)),
        0x19 => $this.ora($mem, AddressMode::AbsoluteIndexed(Register8::Y)),
        0x01 => $this.ora($mem, AddressMode::IndexedIndirect(Register8::X)),
        0x11 => $this.ora($mem, AddressMode::IndirectIndexed(Register8::Y)),

        0x49 => $this.eor($mem, AddressMode::Immediate),
        0x45 => $this.eor($mem, AddressMode::ZeroPage),
        0x55 => $this.eor($mem, AddressMode::ZeroPageIndexed(Register8::X)),
        0x4D => $this.eor($mem, AddressMode::Absolute),
        0x5D => $this.eor($mem, AddressMode::AbsoluteIndexed(Register8::X)),
        0x59 => $this.eor($mem, AddressMode::AbsoluteIndexed(Register8::Y)),
        0x41 => $this.eor($mem, AddressMode::IndexedIndirect(Register8::X)),
        0x51 => $this.eor($mem, AddressMode::IndirectIndexed(Register8::Y)),

        0x38 => $this.sec(),
        0x18 => $this.clc(),
        0x78 => $this.sei(),
        0x58 => $this.cli(),
        0xF8 => $this.sed(),
        0xD8 => $this.cld(),
        0xB8 => $this.clv(),

        0x4C => $this.jmp($mem),
        0x6C => $this.jmpi($mem),
        0x30 => $this.bmi($mem),
        0x10 => $this.bpl($mem),
        0x90 => $this.bcc($mem),
        0xB0 => $this.bcs($mem),
        0xF0 => $this.beq($mem),
        0xD0 => $this.bne($mem),
        0x70 => $this.bvs($mem),
        0x50 => $this.bvc($mem),

        0xC9 => $this.cmp($mem, AddressMode::Immediate),
        0xC5 => $this.cmp($mem, AddressMode::ZeroPage),
        0xD5 => $this.cmp($mem, AddressMode::ZeroPageIndexed(Register8::X)),
        0xCD => $this.cmp($mem, AddressMode::Absolute),
        0xDD => $this.cmp($mem, AddressMode::AbsoluteIndexed(Register8::X)),
        0xD9 => $this.cmp($mem, AddressMode::AbsoluteIndexed(Register8::Y)),
        0xC1 => $this.cmp($mem, AddressMode::IndexedIndirect(Register8::X)),
        0xD1 => $this.cmp($mem, AddressMode::IndirectIndexed(Register8::Y)),

        0xE0 => $this.cpx($mem, AddressMode::Immediate),
        0xE4 => $this.cpx($mem, AddressMode::ZeroPage),
        0xEC => $this.cpx($mem, AddressMode::Absolute),

        0xC0 => $this.cpy($mem, AddressMode::Immediate),
        0xC4 => $this.cpy($mem, AddressMode::ZeroPage),
        0xCC => $this.cpy($mem, AddressMode::Absolute),

        0x24 => $this.bit($mem, AddressMode::ZeroPage),
        0x2C => $this.bit($mem, AddressMode::Absolute),

        0xE6 => $this.inc($mem, AddressMode::ZeroPage),
        0xF6 => $this.inc($mem, AddressMode::ZeroPageIndexed(Register8::X)),
        0xEE => $this.inc($mem, AddressMode::Absolute),
        0xFE => $this.inc($mem, AddressMode::AbsoluteIndexed(Register8::X)),

        0xC6 => $this.dec($mem, AddressMode::ZeroPage),
        0xD6 => $this.dec($mem, AddressMode::ZeroPageIndexed(Register8::X)),
        0xCE => $this.dec($mem, AddressMode::Absolute),
        0xDE => $this.dec($mem, AddressMode::AbsoluteIndexed(Register8::X)),

        0xE8 => $this.inx(),
        0xC8 => $this.iny(),
        0xCA => $this.dex(),
        0x88 => $this.dey(),

        0xAA => $this.tax(),
        0x8A => $this.txa(),
        0xA8 => $this.tay(),
        0x98 => $this.tya(),
        0xBA => $this.tsx(),
        0x9A => $this.txs(),

        0x20 => $this.jsr($mem),
        0x60 => $this.rts($mem),

        0x48 => $this.pha($mem),
        0x68 => $this.pla($mem),
        0x08 => $this.php($mem),
        0x28 => $this.plp($mem),

        0x4A => $this.lsr($mem, AddressMode::Register(Register8::A)),
        0x46 => $this.lsr($mem, AddressMode::ZeroPage),
        0x56 => $this.lsr($mem, AddressMode::ZeroPageIndexed(Register8::X)),
        0x4E => $this.lsr($mem, AddressMode::Absolute),
        0x5E => $this.lsr($mem, AddressMode::AbsoluteIndexed(Register8::X)),

        0x0A => $this.asl($mem, AddressMode::Register(Register8::A)),
        0x06 => $this.asl($mem, AddressMode::ZeroPage),
        0x16 => $this.asl($mem, AddressMode::ZeroPageIndexed(Register8::X)),
        0x0E => $this.asl($mem, AddressMode::Absolute),
        0x1E => $this.asl($mem, AddressMode::AbsoluteIndexed(Register8::X)),

        0x6A => $this.ror($mem, AddressMode::Register(Register8::A)),
        0x66 => $this.ror($mem, AddressMode::ZeroPage),
        0x76 => $this.ror($mem, AddressMode::ZeroPageIndexed(Register8::X)),
        0x6E => $this.ror($mem, AddressMode::Absolute),
        0x7E => $this.ror($mem, AddressMode::AbsoluteIndexed(Register8::X)),

        0x2A => $this.rol($mem, AddressMode::Register(Register8::A)),
        0x26 => $this.rol($mem, AddressMode::ZeroPage),
        0x36 => $this.rol($mem, AddressMode::ZeroPageIndexed(Register8::X)),
        0x2E => $this.rol($mem, AddressMode::Absolute),
        0x3E => $this.rol($mem, AddressMode::AbsoluteIndexed(Register8::X)),

        0x00 => $this.brk($mem),
        0x40 => $this.rti($mem),

        0xEA => $this.nop(),

        // Unofficial opcodes
        0x1A | 0x3A | 0x5A | 0x7A | 0xDA | 0xFA => $this.nop(),
        0x80 | 0x82 | 0x89 | 0xC2 | 0xE2 => $this.nop_2_bytes($mem),
        0x8B => $this.xaa($mem),
        0xA7 => $this.lax($mem, AddressMode::ZeroPage),
        0xB7 => $this.lax($mem, AddressMode::ZeroPageIndexed(Register8::Y)),
        0xAF => $this.lax($mem, AddressMode::Absolute),
        0xBF => $this.lax($mem, AddressMode::AbsoluteIndexed(Register8::Y)),
        0xA3 => $this.lax($mem, AddressMode::IndexedIndirect(Register8::X)),
        0xB3 => $this.lax($mem, AddressMode::IndirectIndexed(Register8::Y)),
        0x07 => $this.slo($mem, AddressMode::ZeroPage),
        0x17 => $this.slo($mem, AddressMode::ZeroPageIndexed(Register8::X)),
        0x0F => $this.slo($mem, AddressMode::Absolute),
        0x1B => $this.slo($mem, AddressMode::AbsoluteIndexed(Register8::Y)),
        0x1F => $this.slo($mem, AddressMode::AbsoluteIndexed(Register8::X)),
        0x03 => $this.slo($mem, AddressMode::IndexedIndirect(Register8::X)),
        0x13 => $this.slo($mem, AddressMode::IndirectIndexed(Register8::Y)),

        _ => panic!("Unimplemented op code {:X}", $opcode),
    }
}
}
