use cpu::{AddressMode, Register8};

// Used by Cpu and Disassembler to decode opcodes and handle the instructions
macro_rules! handle_opcode {
($opcode:expr, $this:ident) => {
    match $opcode {
        0xA9 => $this.lda(AddressMode::Immediate),
        0xA5 => $this.lda(AddressMode::ZeroPage),
        0xB5 => $this.lda(AddressMode::ZeroPageIndexed(Register8::X)),
        0xAD => $this.lda(AddressMode::Absolute),
        0xBD => $this.lda(AddressMode::AbsoluteIndexed(Register8::X)),
        0xB9 => $this.lda(AddressMode::AbsoluteIndexed(Register8::Y)),
        0xA1 => $this.lda(AddressMode::IndexedIndirect(Register8::X)),
        0xB1 => $this.lda(AddressMode::IndirectIndexed(Register8::Y)),

        0xA2 => $this.ldx(AddressMode::Immediate),
        0xA6 => $this.ldx(AddressMode::ZeroPage),
        0xB6 => $this.ldx(AddressMode::ZeroPageIndexed(Register8::Y)),
        0xAE => $this.ldx(AddressMode::Absolute),
        0xBE => $this.ldx(AddressMode::AbsoluteIndexed(Register8::Y)),

        0xA0 => $this.ldy(AddressMode::Immediate),
        0xA4 => $this.ldy(AddressMode::ZeroPage),
        0xB4 => $this.ldy(AddressMode::ZeroPageIndexed(Register8::X)),
        0xAC => $this.ldy(AddressMode::Absolute),
        0xBC => $this.ldy(AddressMode::AbsoluteIndexed(Register8::X)),

        0x85 => $this.sta(AddressMode::ZeroPage),
        0x95 => $this.sta(AddressMode::ZeroPageIndexed(Register8::X)),
        0x8D => $this.sta(AddressMode::Absolute),
        0x9D => $this.sta(AddressMode::AbsoluteIndexed(Register8::X)),
        0x99 => $this.sta(AddressMode::AbsoluteIndexed(Register8::Y)),
        0x81 => $this.sta(AddressMode::IndexedIndirect(Register8::X)),
        0x91 => $this.sta(AddressMode::IndirectIndexed(Register8::Y)),

        0x86 => $this.stx(AddressMode::ZeroPage),
        0x96 => $this.stx(AddressMode::ZeroPageIndexed(Register8::Y)),
        0x8E => $this.stx(AddressMode::Absolute),

        0x84 => $this.sty(AddressMode::ZeroPage),
        0x94 => $this.sty(AddressMode::ZeroPageIndexed(Register8::X)),
        0x8C => $this.sty(AddressMode::Absolute),

        0x69 => $this.adc(AddressMode::Immediate),
        0x65 => $this.adc(AddressMode::ZeroPage),
        0x75 => $this.adc(AddressMode::ZeroPageIndexed(Register8::X)),
        0x6D => $this.adc(AddressMode::Absolute),
        0x7D => $this.adc(AddressMode::AbsoluteIndexed(Register8::X)),
        0x79 => $this.adc(AddressMode::AbsoluteIndexed(Register8::Y)),
        0x61 => $this.adc(AddressMode::IndexedIndirect(Register8::X)),
        0x71 => $this.adc(AddressMode::IndirectIndexed(Register8::Y)),

        0xE9 => $this.sbc(AddressMode::Immediate),
        0xE5 => $this.sbc(AddressMode::ZeroPage),
        0xF5 => $this.sbc(AddressMode::ZeroPageIndexed(Register8::X)),
        0xED => $this.sbc(AddressMode::Absolute),
        0xFD => $this.sbc(AddressMode::AbsoluteIndexed(Register8::X)),
        0xF9 => $this.sbc(AddressMode::AbsoluteIndexed(Register8::Y)),
        0xE1 => $this.sbc(AddressMode::IndexedIndirect(Register8::X)),
        0xF1 => $this.sbc(AddressMode::IndirectIndexed(Register8::Y)),

        0x29 => $this.and(AddressMode::Immediate),
        0x25 => $this.and(AddressMode::ZeroPage),
        0x35 => $this.and(AddressMode::ZeroPageIndexed(Register8::X)),
        0x2D => $this.and(AddressMode::Absolute),
        0x3D => $this.and(AddressMode::AbsoluteIndexed(Register8::X)),
        0x39 => $this.and(AddressMode::AbsoluteIndexed(Register8::Y)),
        0x21 => $this.and(AddressMode::IndexedIndirect(Register8::X)),
        0x31 => $this.and(AddressMode::IndirectIndexed(Register8::Y)),

        0x09 => $this.ora(AddressMode::Immediate),
        0x05 => $this.ora(AddressMode::ZeroPage),
        0x15 => $this.ora(AddressMode::ZeroPageIndexed(Register8::X)),
        0x0D => $this.ora(AddressMode::Absolute),
        0x1D => $this.ora(AddressMode::AbsoluteIndexed(Register8::X)),
        0x19 => $this.ora(AddressMode::AbsoluteIndexed(Register8::Y)),
        0x01 => $this.ora(AddressMode::IndexedIndirect(Register8::X)),
        0x11 => $this.ora(AddressMode::IndirectIndexed(Register8::Y)),

        0x49 => $this.eor(AddressMode::Immediate),
        0x45 => $this.eor(AddressMode::ZeroPage),
        0x55 => $this.eor(AddressMode::ZeroPageIndexed(Register8::X)),
        0x4D => $this.eor(AddressMode::Absolute),
        0x5D => $this.eor(AddressMode::AbsoluteIndexed(Register8::X)),
        0x59 => $this.eor(AddressMode::AbsoluteIndexed(Register8::Y)),
        0x41 => $this.eor(AddressMode::IndexedIndirect(Register8::X)),
        0x51 => $this.eor(AddressMode::IndirectIndexed(Register8::Y)),

        0x38 => $this.sec(),
        0x18 => $this.clc(),
        0x78 => $this.sei(),
        0x58 => $this.cli(),
        0xF8 => $this.sed(),
        0xD8 => $this.cld(),
        0xB8 => $this.clv(),

        0x4C => $this.jmp(),
        0x6C => $this.jmpi(),
        0x30 => $this.bmi(),
        0x10 => $this.bpl(),
        0x90 => $this.bcc(),
        0xB0 => $this.bcs(),
        0xF0 => $this.beq(),
        0xD0 => $this.bne(),
        0x70 => $this.bvs(),
        0x50 => $this.bvc(),

        0xC9 => $this.cmp(AddressMode::Immediate),
        0xC5 => $this.cmp(AddressMode::ZeroPage),
        0xD5 => $this.cmp(AddressMode::ZeroPageIndexed(Register8::X)),
        0xCD => $this.cmp(AddressMode::Absolute),
        0xDD => $this.cmp(AddressMode::AbsoluteIndexed(Register8::X)),
        0xD9 => $this.cmp(AddressMode::AbsoluteIndexed(Register8::Y)),
        0xC1 => $this.cmp(AddressMode::IndexedIndirect(Register8::X)),
        0xD1 => $this.cmp(AddressMode::IndirectIndexed(Register8::Y)),

        0xE0 => $this.cpx(AddressMode::Immediate),
        0xE4 => $this.cpx(AddressMode::ZeroPage),
        0xEC => $this.cpx(AddressMode::Absolute),

        0xC0 => $this.cpy(AddressMode::Immediate),
        0xC4 => $this.cpy(AddressMode::ZeroPage),
        0xCC => $this.cpy(AddressMode::Absolute),

        0x24 => $this.bit(AddressMode::ZeroPage),
        0x2C => $this.bit(AddressMode::Absolute),

        0xE6 => $this.inc(AddressMode::ZeroPage),
        0xF6 => $this.inc(AddressMode::ZeroPageIndexed(Register8::X)),
        0xEE => $this.inc(AddressMode::Absolute),
        0xFE => $this.inc(AddressMode::AbsoluteIndexed(Register8::X)),

        0xC6 => $this.dec(AddressMode::ZeroPage),
        0xD6 => $this.dec(AddressMode::ZeroPageIndexed(Register8::X)),
        0xCE => $this.dec(AddressMode::Absolute),
        0xDE => $this.dec(AddressMode::AbsoluteIndexed(Register8::X)),

        0xE8 => $this.inx(),
        0xC8 => $this.iny(),
        0xCA => $this.dex(),
        0x88 => $this.dey(),

        0xAA => $this.tax(),
        0x8A => $this.txa(),
        0xA8 => $this.tay(),
        0x98 => $this.tya(),
        0xBA => $this.tsx(),
        0x9A => $this.txs(),

        0x20 => $this.jsr(),
        0x60 => $this.rts(),

        0x48 => $this.pha(),
        0x68 => $this.pla(),
        0x08 => $this.php(),
        0x28 => $this.plp(),

        0x4A => $this.lsr(AddressMode::Register(Register8::A)),
        0x46 => $this.lsr(AddressMode::ZeroPage),
        0x56 => $this.lsr(AddressMode::ZeroPageIndexed(Register8::X)),
        0x4E => $this.lsr(AddressMode::Absolute),
        0x5E => $this.lsr(AddressMode::AbsoluteIndexed(Register8::X)),

        0x0A => $this.asl(AddressMode::Register(Register8::A)),
        0x06 => $this.asl(AddressMode::ZeroPage),
        0x16 => $this.asl(AddressMode::ZeroPageIndexed(Register8::X)),
        0x0E => $this.asl(AddressMode::Absolute),
        0x1E => $this.asl(AddressMode::AbsoluteIndexed(Register8::X)),

        0x2A => $this.ror(AddressMode::Register(Register8::A)),
        0x26 => $this.ror(AddressMode::ZeroPage),
        0x36 => $this.ror(AddressMode::ZeroPageIndexed(Register8::X)),
        0x2E => $this.ror(AddressMode::Absolute),
        0x3E => $this.ror(AddressMode::AbsoluteIndexed(Register8::X)),

        0x2A => $this.rol(AddressMode::Register(Register8::A)),
        0x26 => $this.rol(AddressMode::ZeroPage),
        0x36 => $this.rol(AddressMode::ZeroPageIndexed(Register8::X)),
        0x2E => $this.rol(AddressMode::Absolute),
        0x3E => $this.rol(AddressMode::AbsoluteIndexed(Register8::X)),

        0x00 => $this.brk(),
        0x40 => $this.rti(),

        0xEA => $this.nop(),

        // Unofficial opcodes
        0x1A | 0x3A | 0x5A | 0x7A | 0xDA | 0xEA | 0xFA => $this.nop(),
        0x80 | 0x82 | 0x89 | 0xC2 | 0xE2 => $this.nop_2_bytes(),
        0x8B => $this.xaa(),
        0xA7 => $this.lax(AddressMode::ZeroPage),
        0xB7 => $this.lax(AddressMode::ZeroPageIndexed(Register8::Y)),
        0xAF => $this.lax(AddressMode::Absolute),
        0xBF => $this.lax(AddressMode::AbsoluteIndexed(Register8::Y)),
        0xA3 => $this.lax(AddressMode::IndexedIndirect(Register8::X)),
        0xB3 => $this.lax(AddressMode::IndirectIndexed(Register8::Y)),
        0x07 => $this.slo(AddressMode::ZeroPage),
        0x17 => $this.slo(AddressMode::ZeroPageIndexed(Register8::X)),
        0x0F => $this.slo(AddressMode::Absolute),
        0x1B => $this.slo(AddressMode::AbsoluteIndexed(Register8::Y)),
        0x1F => $this.slo(AddressMode::AbsoluteIndexed(Register8::X)),
        0x03 => $this.slo(AddressMode::IndexedIndirect(Register8::X)),
        0x13 => $this.slo(AddressMode::IndirectIndexed(Register8::Y)),

        _ => panic!("Unimplemented op code {:X}", $opcode),
    }
}
}
