[package]
name = "sadnes-libretro"
version = "0.1.0"
authors = ["Jason Rodney Hansen <jasonrodneyhansen@gmail.com>"]

[lib]
name = "sadnes_libretro"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.*"
sadnes-core = { path="../sadnes-core" }
serde = "1.0"
serde_json = "1.0"