[package]
name = "rustednes-cli"
version = "0.1.0"
authors = ["Jason Rodney Hansen <jasonrodneyhansen@gmail.com>"]
description = "A CLI frontend for rustednes-core"
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
minifb = "0.11"
rustednes-core = { path = "../rustednes-core" }
time = "0.1"
cpal = "0.10.0"
serde = "1.0"
serde_json = "1.0"
structopt = "0.2.16"
structopt-derive = "0.2.16"
nom = "5.0.0"
rustyline = "5.0.4"
